version: 2.1

workflows:
  build-site:
    jobs:
      - install

jobs:
  install: # this can be any name you choose
    docker:
      - image: node:16
    parallelism: 1

    steps:
      - run:
          name: Dummy artifact
          command: |
            echo "my artifact file" > /tmp/art-1;
      - store_artifacts:
          path: /tmp/art-1
          destination: my-artifact
